"more settings on http://amix.dk/vim/vimrc.html

" PATHOGEN {{{
execute pathogen#infect()
" }}}
"
" BASIC STUFF {{{
:set nocompatible
:set t_Co=256
:set number
:set relativenumber
:syntax on
:filetype plugin indent on
:set showmatch
:set matchtime=2
:set nowrap
:set expandtab
:set tabstop=4
:set shiftwidth=4
:set background=dark
:colorscheme tron
:set omnifunc=syntaxcomplete#Complete
:set splitright
:set foldmethod=syntax
:set foldlevelstart=1
:set nobackup
:set nowb
:set noswapfile
:set ignorecase
:set incsearch
:set smartcase
:set wildmenu
:set wildmode=longest:full,full
:set mouse=a
:set autoread
:set colorcolumn=81
" :set cursorcolumn
:set backspace=eol,start,indent
" :set list listchars=tab:»·,trail:·,eol:¶
let g:user_emmet_mode='a'    "enable all function in all mode.

let g:airline_powerline_fonts = 1
let javaScript_fold=1         " JavaScript
let perl_fold=1               " Perl
let php_folding=1             " PHP
let r_syntax_folding=1        " R
let ruby_fold=1               " Ruby
let sh_fold_enabled=1         " sh
let vimsyn_folding='af'       " Vim script
let xml_syntax_folding=1      " XML
" }}}

" PROJECT {{{
let g:project_use_nerdtree=1
set rtp+=~/.vim/bundle/vim-project/
" }}}

" ABBREVIATIONS {{{
:iabbrev functino function
:iabbrev fucntion function
:iabbrev whiel while
:iabbrev @@ helluinster@gmail.com
" }}}

" SETTING FONTS {{{
set anti enc=utf-8
" }}}
